// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD1j-D6sUf_bynWuIJxdYUI5CavjnLJWo',
    appId: '1:694993744314:web:87c6df16b6f88c59c32d83',
    messagingSenderId: '694993744314',
    projectId: 'real-estate-sales-app-dev',
    authDomain: 'real-estate-sales-app-dev.firebaseapp.com',
    storageBucket: 'real-estate-sales-app-dev.firebasestorage.app',
    measurementId: 'G-EBDZD7Q85M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3r-xVLjfuHF6vxoNqNjKSFJUv15XaJ4E',
    appId: '1:694993744314:android:6cc16a3f6945f998c32d83',
    messagingSenderId: '694993744314',
    projectId: 'real-estate-sales-app-dev',
    storageBucket: 'real-estate-sales-app-dev.firebasestorage.app',
  );
}
